import { Instrument } from '../types/index.ts';

export const BENCHMARKS = [
  { symbol: 'NIFTY50', name: 'Nifty 50 Index', basePrice: 24350.50, sector: 'Benchmark' },
  { symbol: 'SENSEX', name: 'BSE Sensex 30', basePrice: 79800.20, sector: 'Benchmark' },
  { symbol: 'NIFTYBANK', name: 'Nifty Bank Index', basePrice: 51200.00, sector: 'Banking' },
  { symbol: 'NIFTYIT', name: 'Nifty IT Index', basePrice: 42100.80, sector: 'Information Technology' },
  { symbol: 'NIFTYAUTO', name: 'Nifty Auto Index', basePrice: 24800.30, sector: 'Automobile' },
];

export const INSTRUMENTS: Instrument[] = [
  {
    symbol: 'INFY',
    name: 'Infosys Limited',
    exchange: 'NSE',
    sector: 'Information Technology',
    industry: 'IT Services & Consulting',
    lotSize: 400,
    basePrice: 1542.30,
    averageDailyVolume: 7800000,
    baselineVolatility: 0.016,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTYIT',
  },
  {
    symbol: 'TCS',
    name: 'Tata Consultancy Services Ltd',
    exchange: 'NSE',
    sector: 'Information Technology',
    industry: 'IT Services & Consulting',
    lotSize: 175,
    basePrice: 3421.50,
    averageDailyVolume: 2400000,
    baselineVolatility: 0.014,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTYIT',
  },
  {
    symbol: 'RELIANCE',
    name: 'Reliance Industries Ltd',
    exchange: 'NSE',
    sector: 'Energy & Petrochemicals',
    industry: 'Oil & Gas Refining',
    lotSize: 250,
    basePrice: 1421.20,
    averageDailyVolume: 9200000,
    baselineVolatility: 0.015,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'HDFCBANK',
    name: 'HDFC Bank Limited',
    exchange: 'NSE',
    sector: 'Banking & Financials',
    industry: 'Private Commercial Bank',
    lotSize: 550,
    basePrice: 1890.10,
    averageDailyVolume: 12500000,
    baselineVolatility: 0.013,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTYBANK',
  },
  {
    symbol: 'ICICIBANK',
    name: 'ICICI Bank Limited',
    exchange: 'NSE',
    sector: 'Banking & Financials',
    industry: 'Private Commercial Bank',
    lotSize: 700,
    basePrice: 1265.40,
    averageDailyVolume: 11000000,
    baselineVolatility: 0.015,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTYBANK',
  },
  {
    symbol: 'TATAMOTORS',
    name: 'Tata Motors Limited',
    exchange: 'NSE',
    sector: 'Automobile',
    industry: 'Passenger & Commercial Vehicles',
    lotSize: 725,
    basePrice: 712.80,
    averageDailyVolume: 14200000,
    baselineVolatility: 0.022,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTYAUTO',
  },
  {
    symbol: 'BHARTIARTL',
    name: 'Bharti Airtel Limited',
    exchange: 'NSE',
    sector: 'Telecommunications',
    industry: 'Telecom Services',
    lotSize: 475,
    basePrice: 1680.50,
    averageDailyVolume: 5100000,
    baselineVolatility: 0.014,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'ITC',
    name: 'ITC Limited',
    exchange: 'NSE',
    sector: 'Consumer Goods',
    industry: 'FMCG & Cigarettes',
    lotSize: 1600,
    basePrice: 478.20,
    averageDailyVolume: 18500000,
    baselineVolatility: 0.011,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'SBIN',
    name: 'State Bank of India',
    exchange: 'NSE',
    sector: 'Banking & Financials',
    industry: 'Public Sector Bank',
    lotSize: 750,
    basePrice: 812.50,
    averageDailyVolume: 16000000,
    baselineVolatility: 0.018,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTYBANK',
  },
  {
    symbol: 'WIPRO',
    name: 'Wipro Limited',
    exchange: 'NSE',
    sector: 'Information Technology',
    industry: 'IT Services & Consulting',
    lotSize: 1500,
    basePrice: 532.10,
    averageDailyVolume: 6700000,
    baselineVolatility: 0.017,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTYIT',
  },
  {
    symbol: 'LT',
    name: 'Larsen & Toubro Limited',
    exchange: 'NSE',
    sector: 'Capital Goods & Infra',
    industry: 'Engineering & Construction',
    lotSize: 150,
    basePrice: 3580.00,
    averageDailyVolume: 2800000,
    baselineVolatility: 0.015,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'BAJFINANCE',
    name: 'Bajaj Finance Limited',
    exchange: 'NSE',
    sector: 'Banking & Financials',
    industry: 'Non-Banking Financial Co (NBFC)',
    lotSize: 125,
    basePrice: 7150.00,
    averageDailyVolume: 1400000,
    baselineVolatility: 0.021,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTYBANK',
  },
  {
    symbol: 'SUNPHARMA',
    name: 'Sun Pharmaceutical Industries Ltd',
    exchange: 'NSE',
    sector: 'Pharmaceuticals',
    industry: 'Formulations & Generics',
    lotSize: 350,
    basePrice: 1780.40,
    averageDailyVolume: 3100000,
    baselineVolatility: 0.013,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'MARUTI',
    name: 'Maruti Suzuki India Limited',
    exchange: 'NSE',
    sector: 'Automobile',
    industry: 'Passenger Cars',
    lotSize: 50,
    basePrice: 12450.00,
    averageDailyVolume: 650000,
    baselineVolatility: 0.016,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTYAUTO',
  },
  {
    symbol: 'KOTAKBANK',
    name: 'Kotak Mahindra Bank Ltd',
    exchange: 'NSE',
    sector: 'Banking & Financials',
    industry: 'Private Commercial Bank',
    lotSize: 400,
    basePrice: 1745.00,
    averageDailyVolume: 4900000,
    baselineVolatility: 0.014,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTYBANK',
  },
  {
    symbol: 'TITAN',
    name: 'Titan Company Limited',
    exchange: 'NSE',
    sector: 'Consumer Discretionary',
    industry: 'Jewelry & Watches',
    lotSize: 175,
    basePrice: 3420.00,
    averageDailyVolume: 1200000,
    baselineVolatility: 0.019,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'ADANIENT',
    name: 'Adani Enterprises Limited',
    exchange: 'NSE',
    sector: 'Metals & Mining',
    industry: 'Trading & Infrastructure',
    lotSize: 300,
    basePrice: 2890.00,
    averageDailyVolume: 3500000,
    baselineVolatility: 0.028,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'HCLTECH',
    name: 'HCL Technologies Limited',
    exchange: 'NSE',
    sector: 'Information Technology',
    industry: 'IT Services & Consulting',
    lotSize: 350,
    basePrice: 1720.00,
    averageDailyVolume: 3900000,
    baselineVolatility: 0.016,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTYIT',
  },
  {
    symbol: 'TATASTEEL',
    name: 'Tata Steel Limited',
    exchange: 'NSE',
    sector: 'Metals & Mining',
    industry: 'Iron & Steel',
    lotSize: 5500,
    basePrice: 148.50,
    averageDailyVolume: 35000000,
    baselineVolatility: 0.024,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'HINDUNILVR',
    name: 'Hindustan Unilever Limited',
    exchange: 'NSE',
    sector: 'Consumer Goods',
    industry: 'Diversified FMCG',
    lotSize: 300,
    basePrice: 2380.00,
    averageDailyVolume: 2200000,
    baselineVolatility: 0.012,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'AXISBANK',
    name: 'Axis Bank Limited',
    exchange: 'NSE',
    sector: 'Banking & Financials',
    industry: 'Private Commercial Bank',
    lotSize: 625,
    basePrice: 1140.00,
    averageDailyVolume: 9800000,
    baselineVolatility: 0.017,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTYBANK',
  },
  {
    symbol: 'NTPC',
    name: 'NTPC Limited',
    exchange: 'NSE',
    sector: 'Energy & Petrochemicals',
    industry: 'Power Generation & Distribution',
    lotSize: 1500,
    basePrice: 385.40,
    averageDailyVolume: 18000000,
    baselineVolatility: 0.016,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'ONGC',
    name: 'Oil & Natural Gas Corp Ltd',
    exchange: 'NSE',
    sector: 'Energy & Petrochemicals',
    industry: 'Oil & Gas Exploration',
    lotSize: 2250,
    basePrice: 245.80,
    averageDailyVolume: 22000000,
    baselineVolatility: 0.021,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'POWERGRID',
    name: 'Power Grid Corp of India Ltd',
    exchange: 'NSE',
    sector: 'Energy & Petrochemicals',
    industry: 'Power Transmission',
    lotSize: 1800,
    basePrice: 295.10,
    averageDailyVolume: 15000000,
    baselineVolatility: 0.014,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'M&M',
    name: 'Mahindra & Mahindra Limited',
    exchange: 'NSE',
    sector: 'Automobile',
    industry: 'SUVs & Farm Tractors',
    lotSize: 350,
    basePrice: 2780.00,
    averageDailyVolume: 4200000,
    baselineVolatility: 0.018,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTYAUTO',
  },
  {
    symbol: 'COALINDIA',
    name: 'Coal India Limited',
    exchange: 'NSE',
    sector: 'Metals & Mining',
    industry: 'Coal Mining',
    lotSize: 2100,
    basePrice: 410.50,
    averageDailyVolume: 12000000,
    baselineVolatility: 0.019,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'BAJAJ-AUTO',
    name: 'Bajaj Auto Limited',
    exchange: 'NSE',
    sector: 'Automobile',
    industry: 'Two & Three Wheelers',
    lotSize: 75,
    basePrice: 9150.00,
    averageDailyVolume: 650000,
    baselineVolatility: 0.017,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTYAUTO',
  },
  {
    symbol: 'ULTRACEMCO',
    name: 'UltraTech Cement Limited',
    exchange: 'NSE',
    sector: 'Capital Goods & Infra',
    industry: 'Cement & Building Materials',
    lotSize: 100,
    basePrice: 10850.00,
    averageDailyVolume: 520000,
    baselineVolatility: 0.015,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'NESTLEIND',
    name: 'Nestle India Limited',
    exchange: 'NSE',
    sector: 'Consumer Goods',
    industry: 'Packaged Foods',
    lotSize: 250,
    basePrice: 2280.00,
    averageDailyVolume: 850000,
    baselineVolatility: 0.011,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'JSWSTEEL',
    name: 'JSW Steel Limited',
    exchange: 'NSE',
    sector: 'Metals & Mining',
    industry: 'Steel Production',
    lotSize: 675,
    basePrice: 945.00,
    averageDailyVolume: 5600000,
    baselineVolatility: 0.021,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'TECHM',
    name: 'Tech Mahindra Limited',
    exchange: 'NSE',
    sector: 'Information Technology',
    industry: 'IT & Telecom Services',
    lotSize: 600,
    basePrice: 1580.00,
    averageDailyVolume: 3200000,
    baselineVolatility: 0.019,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTYIT',
  },
  {
    symbol: 'CIPLA',
    name: 'Cipla Limited',
    exchange: 'NSE',
    sector: 'Pharmaceuticals',
    industry: 'Respiratory & Generics',
    lotSize: 650,
    basePrice: 1510.00,
    averageDailyVolume: 2600000,
    baselineVolatility: 0.014,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'DRREDDY',
    name: "Dr. Reddy's Laboratories Ltd",
    exchange: 'NSE',
    sector: 'Pharmaceuticals',
    industry: 'Active Pharma & Biotech',
    lotSize: 125,
    basePrice: 6320.00,
    averageDailyVolume: 1100000,
    baselineVolatility: 0.015,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'APOLLOHOSP',
    name: 'Apollo Hospitals Enterprise Ltd',
    exchange: 'NSE',
    sector: 'Pharmaceuticals',
    industry: 'Healthcare & Hospitals',
    lotSize: 125,
    basePrice: 6850.00,
    averageDailyVolume: 920000,
    baselineVolatility: 0.016,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'EICHERMOT',
    name: 'Eicher Motors Limited',
    exchange: 'NSE',
    sector: 'Automobile',
    industry: 'Royal Enfield Motorcycles',
    lotSize: 175,
    basePrice: 4890.00,
    averageDailyVolume: 980000,
    baselineVolatility: 0.018,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTYAUTO',
  },
  {
    symbol: 'DIVISLAB',
    name: "Divi's Laboratories Limited",
    exchange: 'NSE',
    sector: 'Pharmaceuticals',
    industry: 'Custom Pharma Synthesis',
    lotSize: 200,
    basePrice: 5650.00,
    averageDailyVolume: 780000,
    baselineVolatility: 0.018,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'BPCL',
    name: 'Bharat Petroleum Corp Ltd',
    exchange: 'NSE',
    sector: 'Energy & Petrochemicals',
    industry: 'Fuel Refining & Marketing',
    lotSize: 1800,
    basePrice: 320.00,
    averageDailyVolume: 14000000,
    baselineVolatility: 0.021,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'ZOMATO',
    name: 'Zomato Limited',
    exchange: 'NSE',
    sector: 'Consumer Discretionary',
    industry: 'Food Delivery & Blinkit Quick Commerce',
    lotSize: 2500,
    basePrice: 242.50,
    averageDailyVolume: 42000000,
    baselineVolatility: 0.031,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'JIOFIN',
    name: 'Jio Financial Services Ltd',
    exchange: 'NSE',
    sector: 'Banking & Financials',
    industry: 'Digital Lending, AMC & Insurance',
    lotSize: 2000,
    basePrice: 318.00,
    averageDailyVolume: 28000000,
    baselineVolatility: 0.027,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'TRENT',
    name: 'Trent Limited',
    exchange: 'NSE',
    sector: 'Consumer Discretionary',
    industry: 'Westside & Zudio Retail Chain',
    lotSize: 100,
    basePrice: 6940.00,
    averageDailyVolume: 1900000,
    baselineVolatility: 0.024,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'BEL',
    name: 'Bharat Electronics Limited',
    exchange: 'NSE',
    sector: 'Capital Goods & Infra',
    industry: 'Defense Radar & Avionics',
    lotSize: 2700,
    basePrice: 284.00,
    averageDailyVolume: 26000000,
    baselineVolatility: 0.023,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'HAL',
    name: 'Hindustan Aeronautics Limited',
    exchange: 'NSE',
    sector: 'Capital Goods & Infra',
    industry: 'Aerospace & Defense Aircraft',
    lotSize: 300,
    basePrice: 4280.00,
    averageDailyVolume: 3400000,
    baselineVolatility: 0.026,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  },
  {
    symbol: 'HINDALCO',
    name: 'Hindalco Industries Limited',
    exchange: 'NSE',
    sector: 'Metals & Mining',
    industry: 'Aluminium & Copper Production',
    lotSize: 1400,
    basePrice: 648.00,
    averageDailyVolume: 9200000,
    baselineVolatility: 0.022,
    marketCapCategory: 'LARGE_CAP',
    benchmarkSymbol: 'NIFTY50',
  }
];

export const INSTRUMENT_MAP = new Map<string, Instrument>(
  INSTRUMENTS.map((inst) => [inst.symbol, inst])
);

export function getInstrument(symbol: string): Instrument | undefined {
  return INSTRUMENT_MAP.get(symbol.toUpperCase());
}
